export const FETCH_BLOGS = "FETCH_BLOGS";
export const FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS";
export const ADD_BLOGS = "ADD_BLOGS";
export const ADD_BLOGS_SUCCESS = "ADD_BLOGS_SUCCESS";
export const ERROR = "ERROR";
export const FETCH_BLOG_DETAILS = "FETCH_BLOG_DETAILS";
export const FETCH_BLOG_DETAILS_SUCCESS = "FETCH_BLOG_DETAILS_SUCCESS";
export const ERROR_PAGE = "ERROR_PAGE";
